# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
- repo: https://github.com/jazzband/pip-tools
  rev: b71ab5fd5b92d8cb9774e1f93b5cdafd1a2d24a4
  hooks:
    - id: pip-compile
      files: ^requirements.(in|txt)$
      args: [requirements.in]
    - id: pip-compile
      files: ^(dev|requirements).(in|txt)$
      args: [dev.in]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-added-large-files
# Safety checks
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args:
          - -lll
          - --skip
          - B605
# make code pretty
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: 'master'  # pick a git hash / tag to point to
#    hooks:
#    -   id: flake8
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.5
#    hooks:
#    -   id: autopep8
