swagger: "2.0"
info:
  description: This page describes the available APIs for the Meteo service.  The APIs can also be used directly from here.
  version: "1.0.1"
  title: REST API Description
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /meteo:
    get:
      operationId: "meteo.read_all"
      tags:
        - "Meteo"
      summary: "Returns all weather entries"
      description: "Returns all weather entries"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              properties:
                city:
                  type: "string"
                dt:
                  type: "string"
                temp:
                  type: "string"
                feels_like:
                  type: "string"
                temp_min:
                  type: "string"
                temp_max:
                  type: "string"
                pressure:
                  type: "string"
                sea_level:
                  type: "string"
                grnd_level:
                  type: "string"
                humidity:
                  type: "string"

  /meteo/{city}:
    get:
      operationId: "meteo.read_one"
      tags:
        - "Meteo"
      summary: "Returns weather entries for one city"
      description: "Returns weather entries for a given city"
      parameters:
        - name: city
          in: path
          description: city
          type: string
          required: True
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              properties:
                city:
                  type: "string"
                dt:
                  type: "string"
                temp:
                  type: "string"
                feels_like:
                  type: "string"
                temp_min:
                  type: "string"
                temp_max:
                  type: "string"
                pressure:
                  type: "string"
                sea_level:
                  type: "string"
                grnd_level:
                  type: "string"
                humidity:
                  type: "string"
        404:
          description: "Ressource not found"
